# Generated by Django 4.2 on 2023-05-22 20:26

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=projects.models.default_updated_at),
        ),
    ]
