apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: ingress-nginx
spec:
  rules:
    - host: gear5.online
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: my-django-app-service
                port:
                  number: 8000
