name: CI

on:
    push: 

jobs:
    run-test:
        strategy:
            fail-fast: false
            matrix:
               os: [ubuntu-latest]
               python-version: 
                - "3.10"
                - "3.11"
                - "3.12-dev"

        name: Test
        runs-on: ${{ matrix.os}}
        timeout-minutes: 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache dependencies for Ubuntu
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip  # Path to the dependency cache directory
                key: ${{ matrix.os }}-pip-${{ hashFiles('backend/requirements.txt') }}


            - name: Set up Pyhton
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Upgrade pip
              run: python -m pip install --upgrade pip

            - name: Install dependencies
              run: python -m pip install -r requirements.txt

            - name: Run tests
              run: pytest Portfolio/tests/unit
              continue-on-error: false  # This ensures the build fails if the tests fail


    build:
      needs: run-test
      runs-on: ubuntu-latest  # Adjust the runs-on field as per your requirements
   
      steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Docker image
              run: |
                  cd backend
                  docker build -t pingurl .
