name: Deploy to Docker on VM

on:
  push:
    branches:
      - main

jobs:
 deploy_to_Docker_on_VM:
    runs-on: ubuntu-latest
    steps:
        - name: SSH into Droplet and manage Docker container
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            DROPLET_IP_ADDRESS: ${{ secrets.DROPLET_IP_ADDRESS }}
          run: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
            chmod 600 ssh_key.pem
            ssh -o StrictHostKeyChecking=no -i ./ssh_key.pem serveradmin@${DROPLET_IP_ADDRESS} '

              OLD_IMAGE_ID=$(docker images -q pavelkostyuk/portfolio:latest)
              CONTAINER_ID=$(docker ps -aqf "ancestor=pavelkostyuk/portfolio")
              if [ -n "$CONTAINER_ID" ]; then
                docker stop $CONTAINER_ID
                docker rm $CONTAINER_ID
              else
                echo "No container found matching the criteria."
              fi
              if [ -n "$OLD_IMAGE_ID" ]; then
                docker rmi -f $OLD_IMAGE_ID
              else
                echo "No old image found matching the criteria."
              fi
                docker pull pavelkostyuk/portfolio:latest
                docker run -d -p 8000:8000 pavelkostyuk/portfolio:latest
              '
