name: CI/CD pipeline for Portfolio

on:
    push:
      branches: [main]
    pull_request:
      branches: [developer]


jobs:
    run-test:
        strategy:
            fail-fast: false
            matrix:
               os: [ubuntu-latest]
               python-version: 
                - "3.10"
                - "3.11"

        name: test_code
        runs-on: ${{ matrix.os}}
        timeout-minutes: 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache dependencies for Ubuntu
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip  # Path to the dependency cache directory
                key: ${{ matrix.os }}-pip-${{ hashFiles('Portfolio/requirements.txt') }}

            - name: Set up Pyhton
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: | 
                  python -m pip install --upgrade pip
                  python -m pip install -r Portfolio/requirements.txt

            - name: Run tests
              run: pytest Portfolio/Portfolio/tests/unit
              continue-on-error: false  # This ensures the build fails if the tests fail

    build_test_push_image:
        needs: run-test

        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Docker image
              run: |
                  docker build -t pavelkostyuk/portfolio Portfolio
        
            - name: Start the application container with superuser setup
              run: |
                  docker run -d -p 8000:8000 --name my-app -e DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }} -e DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }} pavelkostyuk/portfolio

            - name: Wait for the app to start
              run: sleep 15

            - name: List running container
              run: docker ps -a

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                spec: cypress/e2e/spec.cy.js
              continue-on-error: false

            - name: Push Docker image to Docker Hub
              run: |
                  echo ${{ secrets.DIGITALOCEAN_API_TOKEN }} | docker login -u pavelkostyuk --password-stdin
                  docker push pavelkostyuk/portfolio

